### ISSUE TITLE
Failed building simulation causes postprocessing to fail

### ISSUE THREAD

**Issue by nmerket** [NREL/buildstockbatch#180]
**Describe the bug**

It started with an unexplainable error in postprocessing

```
DEBUG:2020-07-21 23:12:29:__main__:Starting postprocessing
Traceback (most recent call last):
  File "/shared-projects/buildstock/envs/buildstock-0.18/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/shared-projects/buildstock/envs/buildstock-0.18/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/shared-projects/buildstock/envs/buildstock-0.18/lib/python3.7/site-packages/buildstockbatch/eagle.py", line 751, in <module>
    main()
  File "/shared-projects/buildstock/envs/buildstock-0.18/lib/python3.7/site-packages/buildstockbatch/utils.py", line 61, in run_with_error_capture
    return func(*args, **kwargs)
  File "/shared-projects/buildstock/envs/buildstock-0.18/lib/python3.7/site-packages/buildstockbatch/eagle.py", line 741, in main
    batch.process_results()
  File "/shared-projects/buildstock/envs/buildstock-0.18/lib/python3.7/site-packages/buildstockbatch/base.py", line 773, in process_results
    postprocessing.combine_results(fs, self.results_dir, self.cfg, do_timeseries=do_timeseries)
  File "/shared-projects/buildstock/envs/buildstock-0.18/lib/python3.7/site-packages/buildstockbatch/postprocessing.py", line 265, in combine_results
    dpout['job_id'] = job_id
TypeError: 'NoneType' object does not support item assignment
```

**To Reproduce**

This is kind of tricky since it doesn't happen very often, only when a simulation fails such that a data_point_out.json isn't created.

**Expected behavior**

Postprocessing to move on and include a row in the results.csv indicating the simulation failed.

**Platform (please complete the following information):**
- Simulation platform: Eagle, I think.
- BuildStockBatch version, branch, or sha: ?
- OpenStudio-BuildStock version, branch, or sha: ?
- Local Desktop OS: ?

cc @afontani

**Comment by lixiliu** [comment]
As discussed with @afontani, this could be a wall time issue, where no simulation file is output before a node times out. I had the same error in a recent upgrade run. When I upped my min_per_sim from 30 to 60 (this is for SFD only), I no longer had the 'NoneType' object error. I believe #196 is related to this error as well.

**Comment by nmerket** [comment]
Duplicate to #196
