### ISSUE TITLE
TypeError in bs-0.19

### ISSUE THREAD

**Issue by vtnate** [NREL/buildstockbatch#206]
**Describe the bug**
Postprocessing fails with:

> Traceback (most recent call last):
  File "/shared-projects/buildstock/envs/buildstock-0.19/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/shared-projects/buildstock/envs/buildstock-0.19/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/shared-projects/buildstock/envs/buildstock-0.19/lib/python3.7/site-packages/buildstockbatch/eagle.py", line 757, in <module>
    main()
  File "/shared-projects/buildstock/envs/buildstock-0.19/lib/python3.7/site-packages/buildstockbatch/utils.py", line 61, in run_with_error_capture
    return func(*args, **kwargs)
  File "/shared-projects/buildstock/envs/buildstock-0.19/lib/python3.7/site-packages/buildstockbatch/eagle.py", line 747, in main
    batch.process_results()
  File "/shared-projects/buildstock/envs/buildstock-0.19/lib/python3.7/site-packages/buildstockbatch/base.py", line 779, in process_results
    postprocessing.combine_results(fs, self.results_dir, self.cfg, do_timeseries=do_timeseries)
  File "/shared-projects/buildstock/envs/buildstock-0.19/lib/python3.7/site-packages/buildstockbatch/postprocessing.py", line 332, in combine_results
    mean_mem = np.mean(dask.compute(map(get_ts_mem_usage_d, random.sample(ts_filenames, sample_size)))[0])
  File "<__array_function__ internals>", line 6, in mean
  File "/shared-projects/buildstock/envs/buildstock-0.19/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 3373, in mean
    out=out, **kwargs)
  File "/shared-projects/buildstock/envs/buildstock-0.19/lib/python3.7/site-packages/numpy/core/_methods.py", line 172, in _mean
    ret = ret / rcount
TypeError: unsupported operand type(s) for /: 'map' and 'int'

The yml file that lead to this error can be [found here](https://github.com/NREL/buildstockbatch/blob/type-error/test_yaml.yml).

**To Reproduce**
1. Use the linked yml file with buildstock-0.19
3. Do a normal run. I've been getting 50-60 buildings in buildstock.csv, so perhaps n_datapoints could be reduced a little. `postprocessing.out` is where the error shows up.

**Platform (please complete the following information):**
- Simulation platform: Eagle
- BuildStockBatch version, branch, or sha: buildstock-0.19
- resstock or comstock repo version, branch, or sha: resstock develop
- Local Desktop OS: Mac

**Additional context**
I'm testing in preparation for a larger run, with the same down-selection.

**Comment by rajeee** [comment]
@vtnate Can you attach buildstockbatch_crash_details.log here?

**Comment by vtnate** [comment]
@rajeee I've uploaded the crash details file [on my branch](https://github.com/NREL/buildstockbatch/blob/type-error/test_buildstockbatch_crash_details.log).

I also see that this appears to be a duplicate of the issue @lixiliu raised: #199, which tells me the immediate solution is for me to change my upgrades. I'm good in the short term regarding this. @nmerket

**Comment by rajeee** [comment]
@vtnate Thanks. Yeah, it's failing because there are no time series files for the current upgrade.  Though the error could be made a bit more descriptive and we should definitely allow for some upgrades not having any timeseries result.

**Comment by vtnate** [comment]
Thanks @rajeee, it would be great if upgrades that weren't applicable could still be added to the yml and just resulted in empty timeseries for that upgrade.
