### ISSUE TITLE
Include multiple counties + building attributes in sampler downselect without error or crash

### ISSUE THREAD

**Issue by whiphi92** [NREL/buildstockbatch#250]
**Describe the bug**
I would like to run downselect logic that includes multiple specified counties as well as household attributes. Buildstock Eagle's yml check flags an error when the `sampler` block's `logic` includes downselects for household attributes and multiple county attributes using the operator `or:`. 

**To Reproduce**
Steps to reproduce the behavior using `national_baseline.yml` in resstock develop branch:

```
sampler:
  type: residential_quota_downselect
  args:
    n_datapoints: 3000
    logic:
      - Geometry Building Type ACS|Single-Family Detached
      - Vacancy Status|Occupied
      or:
        - County|AZ, Maricopa County
        - County|CA, Los Angeles County
        - County|GA, Fulton County
        - County|IL, Cook County
        - County|TX, Harris County
        - County|WA, King County
    resample: false
```

**Expected behavior**
A successful ResStock run that downselects on the given Geometry Building Type ACS, Vacancy Status, and specified counties.

**Logs**

```
Traceback (most recent call last):
  File "/shared-projects/buildstock/envs/buildstock-0.20/bin/buildstock_eagle", line 8, in <module>
    sys.exit(user_cli())
  File "/shared-projects/buildstock/envs/buildstock-0.20/lib/python3.7/site-packages/buildstockbatch/eagle.py", line 612, in user_cli
    cfg = yaml.load(f, Loader=yaml.SafeLoader)
  File "/shared-projects/buildstock/envs/buildstock-0.20/lib/python3.7/site-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/shared-projects/buildstock/envs/buildstock-0.20/lib/python3.7/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "/shared-projects/buildstock/envs/buildstock-0.20/lib/python3.7/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/shared-projects/buildstock/envs/buildstock-0.20/lib/python3.7/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/shared-projects/buildstock/envs/buildstock-0.20/lib/python3.7/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/shared-projects/buildstock/envs/buildstock-0.20/lib/python3.7/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/shared-projects/buildstock/envs/buildstock-0.20/lib/python3.7/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/shared-projects/buildstock/envs/buildstock-0.20/lib/python3.7/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/shared-projects/buildstock/envs/buildstock-0.20/lib/python3.7/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/shared-projects/buildstock/envs/buildstock-0.20/lib/python3.7/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/shared-projects/buildstock/envs/buildstock-0.20/lib/python3.7/site-packages/yaml/composer.py", line 82, in compose_node
    node = self.compose_sequence_node(anchor)
  File "/shared-projects/buildstock/envs/buildstock-0.20/lib/python3.7/site-packages/yaml/composer.py", line 110, in compose_sequence_node
    while not self.check_event(SequenceEndEvent):
  File "/shared-projects/buildstock/envs/buildstock-0.20/lib/python3.7/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/shared-projects/buildstock/envs/buildstock-0.20/lib/python3.7/site-packages/yaml/parser.py", line 393, in parse_block_sequence_entry
    "expected <block end>, but found %r" % token.id, token.start_mark)
yaml.parser.ParserError: while parsing a block collection
  in "/home/pwhite/resstock_develop/resstock/project_national/national_baseline.yml", line 13, column 7
expected <block end>, but found '?'
  in "/home/pwhite/resstock_develop/resstock/project_national/national_baseline.yml", line 15, column 7
```

**Platform (please complete the following information):**
- Simulation platform: Eagle
- BuildStockBatch version, branch, or sha: buildstock-0.20
- resstock or comstock repo version, branch, or sha: develop commit 1f93899cf9fb78bf44029f5012a681ede686d2c6
- Local Desktop OS: Windows

**Additional context**
I _believe_ this logic would work on ResStock, but the yml parser is throwing an error about syntax. 

Also, this might be user error on the logic syntax. I reviewed the documentation and think I have it right here.

**Comment by whiphi92** [comment]
I modified the `sampler` block to the following: 

```
sampler:
  type: residential_quota_downselect
  args:
    n_datapoints: 3000
    logic:
      or:
        - County|AZ, Maricopa County
        - County|CA, Los Angeles County
        - County|GA, Fulton County
        - County|IL, Cook County
        - County|TX, Harris County
        - County|WA, King County
      and:
        - Geometry Building Type ACS|Single-Family Detached
        - Vacancy Status|Occupied
    resample: false
```

This syntax does not get flagged by the yml validation, it goes through.

It does result in a buildstock crash, though. Here is the full crash log description.

```

####################
Traceback (most recent call last):
  File "/shared-projects/buildstock/envs/buildstock-0.20/lib/python3.7/site-packages/buildstockbatch/utils.py", line 98, in run_with_error_capture
    return func(*args, **kwargs)
  File "/shared-projects/buildstock/envs/buildstock-0.20/lib/python3.7/site-packages/buildstockbatch/eagle.py", line 711, in main
    batch.run_batch(sampling_only)
  File "/shared-projects/buildstock/envs/buildstock-0.20/lib/python3.7/site-packages/buildstockbatch/eagle.py", line 167, in run_batch
    buildstock_csv_filename = self.sampler.run_sampling()
  File "/shared-projects/buildstock/envs/buildstock-0.20/lib/python3.7/site-packages/buildstockbatch/sampler/downselect.py", line 124, in run_sampling
    df_new = df[self.downselect_logic(df, self.logic)]
  File "/shared-projects/buildstock/envs/buildstock-0.20/lib/python3.7/site-packages/buildstockbatch/sampler/downselect.py", line 80, in downselect_logic
    assert (len(logic) == 1)
AssertionError

In file: /shared-projects/buildstock/envs/buildstock-0.20/lib/python3.7/site-packages/buildstockbatch/utils.py, module run_with_error_capture line: 98 
Local Variables: 'args':()
'kwargs':{}
'f':<_io.TextIOWrapper name='buildstockbatch_crash_details.log' mode='a' encoding='UTF-8'>
'text':'
####################
'
'func':<function main at 0x2b754591f5f0>
'output_file':'buildstockbatch_crash_details.log'

In file: /shared-projects/buildstock/envs/buildstock-0.20/lib/python3.7/site-packages/buildstockbatch/eagle.py, module main line: 711 
Local Variables: 'parser':ArgumentParser(prog='eagle.py', usage=None, description=None, formatter_class=<class 'argparse.HelpFormatter'>, conflict_handler='error', add_help=True)
'args':Namespace(project_filename='/home/pwhite/resstock_develop/resstock/project_national/national_baseline.yml')
'batch':<__main__.EagleBatch object at 0x2b754591db10>
'job_array_number':'0'
'post_process':False
'upload_only':False
'measures_only':False
'sampling_only':True

In file: /shared-projects/buildstock/envs/buildstock-0.20/lib/python3.7/site-packages/buildstockbatch/eagle.py, module run_batch line: 167 
Local Variables: 'self':<__main__.EagleBatch object at 0x2b754591db10>
'sampling_only':True
'sim_out_ts_dir':/scratch/pwhite/national_baseline_testv3/results/simulation_output/timeseries
'i':'0'
'destination_dir':'/scratch/pwhite/national_baseline_testv3/housing_characteristics'

In file: /shared-projects/buildstock/envs/buildstock-0.20/lib/python3.7/site-packages/buildstockbatch/sampler/downselect.py, module run_sampling line: 124 
Local Variables: 'self':<buildstockbatch.sampler.residential_quota.ResidentialQuotaDownselectSampler object at 0x2b754550de90>
'buildstock_csv_filename':'/scratch/pwhite/national_baseline_testv3/housing_characteristics/buildstock.csv'
'df':           Schedules Usage Level  ... CEC Climate Zone REEDS Balancing Area
Building                          ...                                      
1         Stochastic      Medium  ...             None                   98
2         Stochastic        High  ...             None                  115
3         Stochastic      Medium  ...             None                   50
4         Stochastic         Low  ...             None                  127
5         Stochastic        High  ...             None                  125
...              ...         ...  ...              ...                  ...
2996      Stochastic         Low  ...             None                  126
2997      Stochastic         Low  ...             None                   81
2998      Stochastic        High  ...             None                  101
2999      Stochastic      Medium  ...             None                  127
3000      Stochastic         Low  ...             None                  114

[3000 rows x 121 columns]
'n_samples':'3000'
'sampler':<buildstockbatch.sampler.residential_quota.ResidentialQuotaSampler object at 0x2b754591dbd0>
'f_out':<gzip on 0x2b7545523250>
'f_in':<_io.BufferedReader name='/scratch/pwhite/national_baseline_testv3/housing_characteristics/buildstock.csv'>

In file: /shared-projects/buildstock/envs/buildstock-0.20/lib/python3.7/site-packages/buildstockbatch/sampler/downselect.py, module downselect_logic line: 80 
Local Variables: 'cls':<class 'buildstockbatch.sampler.residential_quota.ResidentialQuotaDownselectSampler'>
'df':           Schedules Usage Level  ... CEC Climate Zone REEDS Balancing Area
Building                          ...                                      
1         Stochastic      Medium  ...             None                   98
2         Stochastic        High  ...             None                  115
3         Stochastic      Medium  ...             None                   50
4         Stochastic         Low  ...             None                  127
5         Stochastic        High  ...             None                  125
...              ...         ...  ...              ...                  ...
2996      Stochastic         Low  ...             None                  126
2997      Stochastic         Low  ...             None                   81
2998      Stochastic        High  ...             None                  101
2999      Stochastic      Medium  ...             None                  127
3000      Stochastic         Low  ...             None                  114

[3000 rows x 121 columns]
'logic':{'or': ['County|AZ, Maricopa County','County|CA, Los Angeles County','County|GA, Fulton County','County|IL, Cook County','County|TX, Harris County','County|WA, King County'],'and': ['Geometry Building Type ACS|Single-Family Detached','Vacancy Status|Occupied']}
```

**Comment by shorowit** [comment]
@whiphi92 In the first case, I think your YAML is not valid. Does it work if you add a hyphen before the `or`? That is at least consistent with [the documentation for combining logic](https://buildstockbatch.readthedocs.io/en/latest/filtering_logic.html#combining-logic).

```
      - Geometry Building Type ACS|Single-Family Detached
      - Vacancy Status|Occupied
      - or:
        - County|AZ, Maricopa County
        - County|CA, Los Angeles County
        - County|GA, Fulton County
        - County|IL, Cook County
        - County|TX, Harris County
        - County|WA, King County
```

**Comment by whiphi92** [comment]
@shorowit That worked, thank you for pointing out the details I overlooked! Closing the issue.
