### ISSUE TITLE
Unable to run basic AWS job

### ISSUE THREAD

**Issue by sudeepy** [NREL/buildstockbatch#277]
**Describe the bug**
I'm new to `buildstockbatch`. I've successfully run it locally, but when I try to run on AWS, it hangs while building the Docker image.

**To Reproduce**
1. Download `buildstockbatch` v0.21.
2. Here's my YAML:
```
schema_version: '0.3'
buildstock_directory: ../resstock-2.5.0  # Relative to this file or absolute
project_directory: project_national  # Relative to buildstock_directory
output_directory: ./test_output_downselect
# weather_files_url: https://data.nrel.gov/system/files/156/BuildStock_TMY3_FIPS.zip
weather_files_path: ./weather/BuildStock_TMY3_FIPS.zip  # Relative to this file or absolute path to zipped weather files

sampler:
  type: residential_quota_downselect
  args:
    n_datapoints: 1
    logic:
      - County|IN, Lake County
    resample: true

workflow_generator:
  type: residential_default
  args:
    timeseries_csv_export:
      reporting_frequency: Hourly
      include_enduse_subcategories: true

baseline:
  n_buildings_represented: 133172057  # Total number of residential dwelling units in contiguous United States, including unoccupied units, resulting from a census tract level query of ACS 5-yr 2016 (i.e. 2012-2016), using this script: https://github.com/NREL/resstock-estimation/blob/master/sources/spatial/tsv_maker.py.

upgrades:
  - upgrade_name: Triple-Pane Windows
    options:
      - option: Windows|Triple, Low-E, Non-metal, Air, L-Gain
#        apply_logic:
        costs:
          - value: 45.77
            multiplier: Window Area (ft^2)
        lifetime: 30

aws:
  # The job_identifier should be unique, start with alpha, not include dashes, and limited to 10 chars or data loss can occur
  job_identifier: crrnthmtst
  s3:
    bucket: buildstockbatchoutput
    prefix: testing/first_test
  emr:
    worker_instance_count: 1
  region: us-west-1
  use_spot: true
  batch_array_size: 10
  # To receive email updates on job progress accept the request to receive emails that will be sent from Amazon
  notifications_email: sudeepy@currenthomes.io

```
3. I modified the `Dockerfile` to reference OpenStudio 3.3.0.
4. run `buildstock_aws project_test.yml`
5. Observe hanging during step `Building docker image`

Here's the trace that prints when I kill the command:

```
(buildstockbatch-0.21) sudeepy@sudeepy-m1-mbp buildstockbatch-0.21 % buildstock_aws project_test.yml

     _ __         _     __,              _ __
    ( /  )    o  //   /(    _/_       / ( /  )     _/_    /
     /--< , ,,  // __/  `.  /  __ _, /<  /--< __,  /  _, /
    /___/(_/_(_(/_(_/_(___)(__(_)(__/ |_/___/(_/(_(__(__/ /_
      Executing BuildStock projects with grace since 2018


INFO:2022-03-20 14:03:28:buildstockbatch.base:Base Validation Successful
DEBUG:2022-03-20 14:03:29:buildstockbatch.base:Using OpenStudio version: 3.3.0 with SHA: ad235ff36e
DEBUG:2022-03-20 14:03:29:buildstockbatch.aws.aws:Building docker image
^CTraceback (most recent call last):
  File "/Users/sudeepy/.local/share/virtualenvs/buildstockbatch-0.21-sTzXoU_Z/bin/buildstock_aws", line 8, in <module>
    sys.exit(main())
  File "/Users/sudeepy/.local/share/virtualenvs/buildstockbatch-0.21-sTzXoU_Z/lib/python3.9/site-packages/buildstockbatch/utils.py", line 98, in run_with_error_capture
    return func(*args, **kwargs)
  File "/Users/sudeepy/.local/share/virtualenvs/buildstockbatch-0.21-sTzXoU_Z/lib/python3.9/site-packages/buildstockbatch/aws/aws.py", line 2185, in main
    batch.build_image(args.directory)
  File "/Users/sudeepy/.local/share/virtualenvs/buildstockbatch-0.21-sTzXoU_Z/lib/python3.9/site-packages/buildstockbatch/aws/aws.py", line 1733, in build_image
    self.docker_client.images.build(
  File "/Users/sudeepy/.local/share/virtualenvs/buildstockbatch-0.21-sTzXoU_Z/lib/python3.9/site-packages/docker/models/images.py", line 283, in build
    for chunk in internal_stream:
  File "/Users/sudeepy/.local/share/virtualenvs/buildstockbatch-0.21-sTzXoU_Z/lib/python3.9/site-packages/docker/utils/json_stream.py", line 61, in split_buffer
    for data in stream_as_text(stream):
  File "/Users/sudeepy/.local/share/virtualenvs/buildstockbatch-0.21-sTzXoU_Z/lib/python3.9/site-packages/docker/utils/json_stream.py", line 17, in stream_as_text
    for data in stream:
  File "/Users/sudeepy/.local/share/virtualenvs/buildstockbatch-0.21-sTzXoU_Z/lib/python3.9/site-packages/docker/api/client.py", line 349, in _stream_helper
    data = reader.read(1)
  File "/Users/sudeepy/.local/share/virtualenvs/buildstockbatch-0.21-sTzXoU_Z/lib/python3.9/site-packages/urllib3/response.py", line 522, in read
    data = self._fp.read(amt) if not fp_closed else b""
  File "/Users/sudeepy/.pyenv/versions/3.9.7/lib/python3.9/http/client.py", line 462, in read
    n = self.readinto(b)
  File "/Users/sudeepy/.pyenv/versions/3.9.7/lib/python3.9/http/client.py", line 496, in readinto
    return self._readinto_chunked(b)
  File "/Users/sudeepy/.pyenv/versions/3.9.7/lib/python3.9/http/client.py", line 591, in _readinto_chunked
    chunk_left = self._get_chunk_left()
  File "/Users/sudeepy/.pyenv/versions/3.9.7/lib/python3.9/http/client.py", line 559, in _get_chunk_left
    chunk_left = self._read_next_chunk_size()
  File "/Users/sudeepy/.pyenv/versions/3.9.7/lib/python3.9/http/client.py", line 519, in _read_next_chunk_size
    line = self.fp.readline(_MAXLINE + 1)
  File "/Users/sudeepy/.pyenv/versions/3.9.7/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
KeyboardInterrupt

```

**Expected behavior**
The image should be built and pushed to ECR, and when it's done running, I should get an email.

**Logs**
I'm new to Docker and `buildstockbatch`; so unfortunately I don't see any other pertinent logs. When I look at the Docker UI, I see `Error response from daemon: configured logging driver does not support reading`

**Platform (please complete the following information):**
- Simulation platform: AWS
- BuildStockBatch version, branch, or sha: v0.21
- resstock or comstock repo version, branch, or sha: resstock 2.5.0
- Local Desktop OS: Mac, macos Montery 12.3
- Docker Desktop: 4.6.0 (75818)

**Additional context**
None

**Comment by nmerket** [comment]
This isn't broken, it can just take a long time. The base nrel/openstudio image is large and can take a while to download and then there is adding all the other dependencies (building python, instaling packages). It can take many minutes to run, especially the first time. It's also dependent on your internet speed.

That being said the AWS batch version is best effort and we're not in a position to provide much user support, so your mileage may vary.
