### ISSUE TITLE
"out of space" error when there is space

### ISSUE THREAD

**Issue by ekpresent** [NREL/buildstockbatch#279]
**Describe the bug**
When running bsb with develop as of 3/16, using some ways of specifying the weather files gives an out of space error.

**To Reproduce**
1. YAML: https://github.com/NREL/resstock/pull/848/commits/99bad8ddd2b9021a002ce8197abeeda96fbc8358  
  (In case that's the wrong way to specify it: you want the "PR-test.yml" from commit 99bad8ddd2b9021a002ce8197abeeda96fbc8358, branch "incremental-costs" of resstock repo
Note that the updated YAML in 
commit 231d258b12be86f1502b28b6e779aeefbdb9bfa9 ran successfully with a change to the weather file specification
2. Ran on eagle using my scratch directory for both resstock repo and output storage (also failed in several other configurations, including using my home directory for resstock repo and projects/enduse for output storage)

**Expected behavior**
Ideally, it should run. If it cannot run, it should give a more useful error message.

**Logs**

sampling.out

Job ID: 8765993
Hostname: r6i5n17
QOS: normal
DEBUG:2022-03-18 15:16:30:buildstockbatch.base:Using OpenStudio version: 3.3.0 with SHA: ad235ff36e
DEBUG:2022-03-18 15:16:30:__main__:Output directory = /lustre/eaglefs/scratch/epresent/PR848test/PRtest7
DEBUG:2022-03-18 15:16:30:buildstockbatch.base:Downloading weather files
Traceback (most recent call last):
  File "/shared-projects/buildstock/envs/dev-epresent-hpxml/lib/python3.7/site-packages/buildstockbatch/base.py", line 106, in _get_weather_files
    f.write(chunk)
OSError: [Errno 28] No space left on device

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/shared-projects/buildstock/envs/dev-epresent-hpxml/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/shared-projects/buildstock/envs/dev-epresent-hpxml/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/shared-projects/buildstock/envs/dev-epresent-hpxml/lib/python3.7/site-packages/buildstockbatch/eagle.py", line 741, in <module>
    main()
  File "/shared-projects/buildstock/envs/dev-epresent-hpxml/lib/python3.7/site-packages/buildstockbatch/utils.py", line 98, in run_with_error_capture
    return func(*args, **kwargs)
  File "/shared-projects/buildstock/envs/dev-epresent-hpxml/lib/python3.7/site-packages/buildstockbatch/eagle.py", line 709, in main
    batch = EagleBatch(args.project_filename)
  File "/shared-projects/buildstock/envs/dev-epresent-hpxml/lib/python3.7/site-packages/buildstockbatch/eagle.py", line 70, in __init__
    weather_dir = self.weather_dir  # noqa E841
  File "/shared-projects/buildstock/envs/dev-epresent-hpxml/lib/python3.7/site-packages/buildstockbatch/eagle.py", line 145, in weather_dir
    self._get_weather_files()
  File "/shared-projects/buildstock/envs/dev-epresent-hpxml/lib/python3.7/site-packages/buildstockbatch/base.py", line 110, in _get_weather_files
    zf.extractall(self.weather_dir)
OSError: [Errno 28] No space left on device

real	0m8.737s
user	0m3.122s
sys	0m3.036s

```
This is the sampling.out, saved as a .txt so Github would let me upload it
[sampling.txt](https://github.com/NREL/buildstockbatch/files/8343860/sampling.txt)
```

**Platform (please complete the following information):**
- Simulation platform: Eagle
- BuildStockBatch version, branch, or sha: I used a dev-epresent-hpxml made using the develop branch of buildstockbatch on 3/16/22. It's available on eagle for others to look at/use.
- resstock or comstock repo version, branch, or sha: see above. resstock/incremental-costs
- Local Desktop OS: Windows but I have to believe that's irrelevant

**Comment by nmerket** [comment]
Is this still happening?

**Comment by rajeee** [comment]
I believe this was Eagle file system issue. Should open another issue if this repeats in Kestrel.
