### ISSUE TITLE
postprocessing crashes when simulation_output_report not in workflow_generator args

### ISSUE THREAD

**Issue by rajeee** [NREL/buildstockbatch#290]
**Describe the bug**
If workflow_generator args doesn't contain  simulation_output_report key in the project yaml, postprocessing crashes

**To Reproduce**
1. Run a simulation with residential_hpxml workflow generator, but without simulation_output_report key in the args

**Expected behavior**
Either fail the validation because simulation_output_report key is missing, or run simulation without timeseries output. Crashing instead during postprocessing is not acceptable

**Logs**

```
Traceback (most recent call last):
  File "/home/radhikar/buildstock/envs/bsb2/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/radhikar/buildstock/envs/bsb2/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/radhikar/buildstock/buildstockbatch2/buildstockbatch/eagle.py", line 750, in <module>
    main()
  File "/home/radhikar/buildstock/buildstockbatch2/buildstockbatch/utils.py", line 98, in run_with_error_capture
    return func(*args, **kwargs)
  File "/home/radhikar/buildstock/buildstockbatch2/buildstockbatch/eagle.py", line 740, in main
    batch.process_results()
  File "/home/radhikar/buildstock/buildstockbatch2/buildstockbatch/base.py", line 603, in process_results
    postprocessing.combine_results(fs, self.results_dir, self.cfg, do_timeseries=do_timeseries)
UnboundLocalError: local variable 'do_timeseries' referenced before assignment
```

**Platform (please complete the following information):**
- Simulation platform: Eagle
- BuildStockBatch version, branch, or sha:  develop
- resstock or comstock repo version, branch, or sha: resstock 
- Local Desktop OS: [e.g. Windows, Mac, Linux, especially important if running locally]

**Additional context**
I think we should write validators for each workflow generators.

**Comment by rajeee** [comment]
Still an issue.
